FROM php:5.6-fpm-alpine

RUN apk update && \
    apk add tzdata && \
    cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime && \
    echo "Europe/Stockholm" > /etc/timezone && \
    apk del tzdata && \
    rm -rf /var/cache/apk/* /var/tmp/* /tmp/*

COPY docker/fpm.conf /usr/local/etc/php-fpm.d/www.conf 

WORKDIR /srv
CMD ["php-fpm"]
