ALTER TABLE reviews ADD COLUMN category_id INT;
ALTER TABLE reviews ADD FOREIGN KEY (category_id) REFERENCES categories(id);

UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='web') WHERE category='web';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='tools') WHERE category='tools';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='exam_prep') WHERE category='exam_prep';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='game_development') WHERE category='game_dev';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='security') WHERE category='security';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='cloud') WHERE category='cloud';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='ruby') WHERE category='ruby';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='leadership') WHERE category='leadership';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='performance') WHERE category='performance';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='microsoft') WHERE category='microsoft';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='dotnet') WHERE category='dotnet';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='databases') WHERE category='database';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='tech_other') WHERE category='about_technology';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='agile') WHERE category='agile';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='testing') WHERE category='testing';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='java') WHERE category='j2ee';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='product_ownership') WHERE category='reqs';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='architecture') WHERE category='design';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='code') WHERE category='software_dev';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='sw_engineering') WHERE category='software_eng';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='continuous_delivery') WHERE title like '%Continuous Delivery%';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='agile') WHERE title='Balancing Agility and Discipline: A Guide for the Perplexed';
UPDATE reviews SET category_id=(SELECT id FROM categories WHERE name='architecture') WHERE title='97 Things Every Software Architect Should Know';